apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: odosiisvc2
  name: odosiisvc2
  # namespace: odos-test
spec:
  replicas: 1
  selector:
    deploymentconfig: odosiisvc2
  template:
    metadata:
      labels:
        app: odosiisvc2
        deploymentconfig: odosiisvc2
    spec:
      containers:
        - image: odosiisvc2:latest
          imagePullPolicy: Always
          name: odosiisvc2
          ports:
            - containerPort: 8083
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - odosiisvc2
        from:
          kind: ImageStreamTag
          name: odosiisvc2:latest
          # namespace: odos-test
      type: ImageChange
    - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: odosiisvc2
spec:
  selector:
    docker-registry: default
  ports:
  - nodePort: 0
    port: 8083
    protocol: TCP
    targetPort: 8083
